### ISSUE TITLE
How to run DNN with regression task?

### ISSUE THREAD

**Issue by FitashUlHaq** [coinse/sadl#6]
Hi, I am trying to run DNN with regression task (i.e chauffeur). I have training and test data, while trying to calculate the activation traces in this [file here](https://github.com/coinse/sadl/blob/cea322974168389585e57f7e7ac8f832dfe67a01/sa.py#L41)

the code only calculates for the DNN with classification task, can you please guide me how can I integrate DNNs with regression task? or if you have some other repository I can look into for guidance that will be very helpful.

**Comment by jinhankim** [comment]
You can easily modify the code in order to use SA for non-classification tasks and some code are already there. See the lines https://github.com/coinse/sadl/blob/cea322974168389585e57f7e7ac8f832dfe67a01/sa.py#L270-L274
What you have to do is changing class-based KDE to no-class-based KDE.

Note that DSA is only for classification tasks so LSA many fit for your purpose.
